[versions]
# App & SDK Versions
versionCode = "1"
versionName = "1.0.0"
minSdk = "26"
targetSdk = "36"
compileSdk = "36"
javaVersion = "21"

# Appspiriment Plugin Versions
appspiriment = "LIBVERSION"
appspirimentLogUtils = "0.0.1"
appspirimentUtils = "0.0.5.dev-11"
appspirimentComposeUtils = "0.0.6.dev-78"
appspirimentUpdateUtils = "0.0.1"

# Classpath & Tooling
agp = "8.13.1"
kotlin = "2.3.10"
ksp = "2.3.6"
hilt = "2.58"
kotlinserializeplugin = "2.3.10"

# Core Libraries
coreKtx = "1.17.0"
room = "2.7.2"
kotlinserialize = "1.8.0"
kotlinxCoroutines = "1.10.1"
googleServices = "4.4.3"

# Compose & Lifecycle
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.4"
composeBom = "2026.02.01"
composeNavigation = "2.9.1"
composeHiltNavigation = "1.3.0"
lifecycle = "2.10.0"
material-icons = "1.7.8"

# Networking & Data
retrofit = "2.11.0"
okhttp = "4.12.0"
loggingInterceptor = "4.11.0"
gson = "2.11.0"
chucker = "4.2.0"
datastore = "1.1.1"
security = "1.1.0-alpha06"
tink = "1.15.0"
work = "2.10.0"
hiltWork = "1.2.0"
retrofitSerialization = "2.11.0"

# Tools & Test
lottie = "6.6.0"
firebaseBom = "33.14.0"
firebasecrashlyticsplugin = "3.0.4"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
mockito = "6.2.3"
turbine = "1.1.0"

# Publishing & CI
vanniktechPublish = "0.36.0"
firebaseAppDistribution = "5.1.1"
firebasePerf = "1.4.2"

[libraries]
# Stubs for bundles
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core-android", version.ref = "material-icons" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended-android", version.ref = "material-icons" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
kotlinx-serialize = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinserialize" }
junit-test = { group = "junit", name = "junit", version.ref = "junit" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[bundles]
android-base = [
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx",
    "kotlinx-coroutines-android"
]
android-compose = [
    "androidx-activity-compose",
    "androidx-compose-foundation",
    "androidx-ui",
    "androidx-ui-tooling-preview",
    "androidx-material3",
    "androidx-compose-material-icons-core",
    "androidx-compose-material-icons-extended",
    "androidx-compose-navigation",
    "androidx-lifecycle-viewModelCompose",
    "androidx-lifecycle-runtimeCompose",
    "kotlinx-serialize"
]
unit-test = [
    "junit-test",
    "mockito-kotlin",
    "kotlinx-coroutines-test",
    "turbine"
]

[plugins]
# Root project plugins only
google-android-application = { id = "com.android.application", version.ref = "agp" }
google-android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechPublish" }
google-firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppDistribution" }
google-firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerf" }
google-android-test = { id = "com.android.test", version.ref = "agp" }

# Appspiriment Convention Plugins
appspiriment-application = { id = "io.github.appspiriment.application", version.ref = "appspiriment" }
appspiriment-library = { id = "io.github.appspiriment.library", version.ref = "appspiriment" }
appspiriment-library-compose = { id = "io.github.appspiriment.library-compose", version.ref = "appspiriment" }
appspiriment-library-hilt = { id = "io.github.appspiriment.library-hilt", version.ref = "appspiriment" }
appspiriment-library-hilt-compose = { id = "io.github.appspiriment.library-hilt-compose", version.ref = "appspiriment" }
appspiriment-data = { id = "io.github.appspiriment.data", version.ref = "appspiriment" }
